### ISSUE TITLE
Not refreshing actions instatly to other users

### ISSUE THREAD

**Issue by lopesdynamix** [yuribett/DynaClub#45]
**Actions as asking for donations or cancellation of asking are not refreshing in the other users' screen.**
![image](https://cloud.githubusercontent.com/assets/21042431/25908728/4c8aec60-3581-11e7-90e4-d1539484203a.png)

**Comment by anderson-amorim** [comment]
Verified that this problem is caused by proxy blocking on our WebSocket services. Unfortunately, this problem it's beyond our reach for now.
Tested without proxy and everything works fine. Even with Dynamix's proxy, everything works fine for 99% of the time, showing proof that this is a very random and situational problem.
